# the string generated by gen.py may have the following mistakes: bar0 bar2 bar0 bar1 bar2.
# we use this script to turn it into: bar0 bar1 bar2 bar3 bar4
with open('../data/lmd_matched/lib-min.notes', 'r') as r, open('min.notes', 'w') as w:
    raw_notes = r.readlines()
    for line in raw_notes:
        modified = ''
        # line = 'A 0 X X X A 0 X X X A 0 X X X A 0 X X X A 1 X X X A 0 X X X A 0 X X X A 1 X X X A 1 X X X A 2 X X X A 0 X X X'
        tmp = line.strip().split(' ')
        # print(tmp)
        max_idx = -1
        last_bar_idx = -1
        for i in range(len(tmp) // 5):
            bar_idx = int(tmp[5 * i + 1][4:])
            if bar_idx != last_bar_idx:
                last_bar_idx = bar_idx
                max_idx += 1
            modified += '{} bar_{} {} {} {} '.format(tmp[5 * i], max_idx, tmp[5 * i + 2], tmp[5 * i + 3],
                                                     tmp[5 * i + 4])
        w.write(modified)
        w.write('\n')
        # print(modified)

with open('../data/lmd_matched/lib-maj.notes', 'r') as r, open('maj.notes', 'w') as w:
    raw_notes = r.readlines()
    for line in raw_notes:
        modified = ''
        # line = 'A 0 X X X A 0 X X X A 0 X X X A 0 X X X A 1 X X X A 0 X X X A 0 X X X A 1 X X X A 1 X X X A 2 X X X A 0 X X X'
        tmp = line.strip().split(' ')
        # print(tmp)
        max_idx = -1
        last_bar_idx = -1
        for i in range(len(tmp) // 5):
            bar_idx = int(tmp[5 * i + 1][4:])
            if bar_idx != last_bar_idx:
                last_bar_idx = bar_idx
                max_idx += 1
            modified += '{} bar_{} {} {} {} '.format(tmp[5 * i], max_idx, tmp[5 * i + 2], tmp[5 * i + 3],
                                                     tmp[5 * i + 4])
        w.write(modified)
        w.write('\n')
